<?php
/**
 * Created by PhpStorm.
 * User: reddeath
 * Date: 9/8/2018
 * Time: 6:03 PM
 */
$dir = str_replace('controller','',__DIR__);

include_once ($dir.'/model/main.class.php');
class Bus extends Main
{
    public function __construct()
    {
       parent::__construct();
    }

    public function getBuses($id = false){
        return $this->bus($id);
    }

    public function Elapsed($datetime, $full = false)
    {
        return parent::Elapsed($datetime, $full); // TODO: Change the autogenerated stub
    }
}